
---
swagger: "2.0"
info:
  description: "This is a sample Image Upload server created by Arjun as Part of FLAT-LAY\
    \ training."
  version: "1.0.0"
  title: "Arjun Image Uploader"
  contact:
    email: "nemaniarjun@gmail.com"
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
paths:
  /user:
    post:
      summary: "Add a new user to the neo4j database"
      description: "Takes a json specifying a User, saves it into neo4j and returns the userid."
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "formData"
        description: "name of user"
        required: true
        type: "string"
      
      - name: "email"
        in: "formData"
        description: "email of user"
        required: true
        type: "string"
      
      - name: "birthday"
        in: "formData"
        description: "birthday of user"
        required: true
        type: "string"
      
      - name: "fb"
        in: "formData"
        description: "facebook ID of user"
        required: true
        type: "string"
        
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserResponse"
      x-swagger-router-controller: "user"    
  
  /uploadImage:
    post:
      summary: "saves image to location, returns location"
      description: "Takes an image as a form upload, saves it and returns the location."
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: true
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ImageResponse"
      x-swagger-router-controller: "image"
definitions:
  ImageResponse:
    type: "object"
    properties:
      message:
        type: "string"
      fpath:
        type: "string"
    example:
      fpath: "./imagestore/x.jpg"
      message: "message"
  UserResponse:
    type: "object"
    properties:
      message:
        type: "string"
    example:
      message: "message"